// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use session-mode pooler (port 5432) for CLI operations (migrations, db push)
    // The app runtime uses DATABASE_URL (port 6543) via the PrismaClient adapter
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
